### ISSUE TITLE
HandlerValidatorRoles not found

### ISSUE THREAD

**Issue by amardesi** [BirkbeckCTP/ojs-janeway#1]
What versions of OJS have you tested this with?
We're getting this error when we try to enable this plug-in in our OJS. We're running 2.3.6

```Fatal error: Class 'HandlerValidatorRoles' not found in /apps/eschol/apache/htdocs/ojs/classes/template/TemplateManager.inc.php on line 122```

**Comment by ajrbyers** [comment]
Hi @amardesi, this plugin was tested on 2.4.3. Will generate a branch for 2.4.3 and then we can look at a branch for 2.3.6.

**Comment by amardesi** [comment]
Andy B,

Bug described above was generated from the walkme code (in-context help messages) we added to our fork of OJS. You can close this ticket. This plug-in has been installed, but clicking the "Janeway Export" leads to another problem which I will include in a separate ticket.
- Andy M
