### ISSUE TITLE
Expose Main/Correspondence Author

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/ojs-janeway#3]

**Comment by ajrbyers** [comment]
I don't thing OJS 2 actually has this.......

**Comment by mauromsl** [comment]
I thought this was already implemented here:
https://github.com/BirkbeckCTP/ojs-janeway/blob/d717b166cf2d418063a9713bebac51bc9e1720d5/JanewayHandler.inc.php#L251

**Comment by ajrbyers** [comment]
Nice, I hadn't noticed that.
